[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
aigoal = "95zvvX88Cuy5mWGkpJzawYmh9NqY9ksREPzBcdeWM8WM"

[programs.localnet]
aigoal = "95zvvX88Cuy5mWGkpJzawYmh9NqY9ksREPzBcdeWM8WM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
